name: Pull Request Builder

# Triggered by pull request to main branch
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

# Job Definition
jobs:
  # add running tests
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'validated'
      
      - name: Run tests with .NET
        run: dotnet test .\rest_api_template\