name: Pull Request Builder

# Triggered by pull request to main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

# Job Definition
jobs:
  # add running tests
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test