name: Release

# Trigger on merge to main
on:
  release:
    types: [published]

# Job Definition
jobs:
  Release:
    # publish nuget package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Package .NET Application
        run: dotnet pack .\Tricentis.Rest-API-Template.sln

      - name: Upload Release Asset
        uses: Shopify/upload-to-release@v1
        with:
          name: Rest-API.nupkg
          path: .\src\bin\Release\Tricentis.Rest-API-Template.1.0.0.nupkg
          repo-token: ${{ secrets.GITHUB_TOKEN }}