name: Release

# Trigger on release published
on:
  release:
    types: [published]

# Job Definition
jobs:
  Release:
    # publish nuget package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Package .NET Application
        run: dotnet pack .\Tricentis.RestApi.Template.sln

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: .\src\bin\Release\Tricentis.RestAPI.Template.1.0.0.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}