name: SonarQube

on:
  # Workflow can be triggered manually through the GithubActions UI
  workflow_dispatch:
  # Workflow triggered by all opened, reopened and updated
  pull_request:
    types: [opened, synchronize, reopened]
  # also triggered by release
  release:
    types: [published]
  # Will also run everyday at 4AM UTC
  schedule:
    - cron: "0 4 * * *"
  
jobs:
  # add running tests
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}